name: Hello Node.js

on:
  push:
    branches: [main]  # or "master", depending on your repo's default branch

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # You can change this version if needed

      - name: Say Hello
        run: echo "Hello from varshaa_1616"
